# This is a deploy workflow to help you get started with Actions
name: Deploy using Azure ARM with Azure Free trial (Do not have SubID)

# Controls when the workflow will run
on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]
jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      steps:

        # Checkout code
      - uses: actions/checkout@main

        # Log into Azure
      - name: Run azure/login@v1
        run: echo with free trial, we do get subscription id so it will not login

        # Deploy ARM template
      - name: Run ARM deploy
        run: echo For now used azuredeploy.json ARM template under .github/workflow directory in Azure portal.
